import {AbsoluteFill, Easing, Img, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';

const C = {orange:'#ff6b0a',yellow:'#ffc400',teal:'#00a6bb',ink:'#11100e',paper:'#fffaf0'};
const display = 'Impact, Haettenschweiler, "Arial Black", sans-serif';
const body = 'Georgia, "Times New Roman", serif';
const clamp = {extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const ease = Easing.bezier(.16,1,.3,1);
const pop = Easing.bezier(.34,1.3,.64,1);
const photo={
  ia:staticFile('images/ia.jpeg'),
  modelagem:staticFile('images/modelagem.jpg'),
  oculos:staticFile('images/oculos.jpg'),
  robo:staticFile('images/robo.jpeg'),
};
const enter=(f:number,d=0,n=15,curve=ease)=>interpolate(f,[d,d+n],[0,1],{...clamp,easing:curve});

const Paper=({children,color=C.paper,style}:{children:React.ReactNode;color?:string;style?:React.CSSProperties})=><div style={{position:'relative',zIndex:2,background:color,color:C.ink,padding:'18px 26px 22px',clipPath:'polygon(1% 5%,8% 0,19% 4%,31% 1%,46% 5%,61% 0,76% 4%,91% 1%,99% 8%,97% 91%,88% 97%,69% 94%,55% 100%,38% 96%,21% 99%,5% 93%)',...style}}>{children}</div>;
const Tag=({children,color=C.paper,delay=0,fontSize=112}:{children:React.ReactNode;color?:string;delay?:number;fontSize?:number})=>{const f=useCurrentFrame(),p=enter(f,delay,13,pop);return <Paper color={color} style={{display:'inline-block',opacity:p,scale:.78+p*.22,translate:`${-42*(1-p)}px ${22*(1-p)}px`,boxShadow:`12px 13px 0 ${C.ink}`}}><span style={{fontFamily:display,fontSize,lineHeight:.8,letterSpacing:-2}}>{children}</span></Paper>};

const Background=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:C.orange,overflow:'hidden'}}><div style={{position:'absolute',width:1420,height:390,top:-146,left:-110,background:C.paper,rotate:'-12deg'}}/><div style={{position:'absolute',width:830,height:490,top:-140,right:-380,background:C.teal,rotate:'23deg',opacity:.9}}/><div style={{position:'absolute',width:980,height:840,right:-660,top:620,border:`42px solid ${C.yellow}`,borderRadius:'50%',rotate:`${f/15}deg`,opacity:.72}}/><div style={{position:'absolute',inset:-100,opacity:.14,backgroundImage:'repeating-radial-gradient(circle at 0 0,#fff 0 1px,transparent 1px 5px),repeating-linear-gradient(72deg,transparent 0 13px,rgba(0,0,0,.4) 14px 15px)',backgroundPosition:`${f*3}px ${f*-2}px`,mixBlendMode:'overlay'}}/><div style={{position:'absolute',width:1350,height:100,left:-180,bottom:295,background:C.yellow,rotate:'-22deg',opacity:.86}}/><div style={{position:'absolute',width:1150,height:48,left:210,bottom:350,background:C.yellow,rotate:'18deg',opacity:.86}}/></AbsoluteFill>};
const Scene=({children}:{children:React.ReactNode})=><AbsoluteFill><Background/><div style={{position:'absolute',inset:'150px 64px 125px',textAlign:'center'}}>{children}</div></AbsoluteFill>;
const Photo=({src,delay=0,right=false}:{src:string;delay?:number;right?:boolean})=>{const f=useCurrentFrame(),p=enter(f,delay,19);return <div style={{position:'absolute',width:940,height:820,left:'50%',marginLeft:-470,bottom:-170,opacity:p,rotate:right?`${4-4*(1-p)}deg`:`${-4+4*(1-p)}deg`,translate:`0 ${120*(1-p)}px`,clipPath:'polygon(4% 8%,97% 0,94% 94%,83% 99%,68% 95%,55% 100%,38% 95%,21% 99%,0 88%)',border:`20px solid ${C.paper}`,boxShadow:`24px 28px 0 ${C.ink}, 0 0 0 12px ${C.yellow}`,zIndex:1}}><Img src={src} style={{width:'100%',height:'100%',objectFit:'cover',filter:'contrast(1.18) saturate(.95)'}}/></div>};

const Intro=()=> <Scene><Tag delay={3} fontSize={106}>SUA ESCOLA</Tag><div style={{height:30}}/><Paper style={{display:'inline-block',fontFamily:body,fontWeight:700,fontSize:42,rotate:'-2deg'}}>está pronta para viver a</Paper><div style={{height:30}}/><Tag color={C.teal} delay={18} fontSize={142}>TECNOLOGIA</Tag><div style={{height:22}}/><Tag color={C.yellow} delay={29} fontSize={128}>NA PRÁTICA?</Tag><Photo src={photo.robo} delay={38} right/></Scene>;
const Offer=()=> <Scene><Photo src={photo.ia}/><div style={{position:'relative',zIndex:2,paddingTop:40}}><Paper style={{fontFamily:body,fontWeight:800,fontSize:49,textAlign:'center',rotate:'2deg'}}>OFICINAS</Paper><div style={{height:24}}/><Tag color={C.teal} delay={9} fontSize={146}>GRATUITAS</Tag><div style={{height:20}}/><Paper style={{display:'inline-block',fontFamily:body,fontWeight:800,fontSize:38,rotate:'-2deg'}}>experiências práticas</Paper><div style={{height:24}}/><Tag color={C.yellow} delay={26} fontSize={110}>CERTIFICAÇÃO</Tag></div></Scene>;
const KitCard=({label,color,delay}:{label:string;color:string;delay:number})=>{const f=useCurrentFrame(),p=enter(f,delay,13,pop);return <Paper color={color} style={{height:230,display:'grid',placeItems:'center',opacity:p,scale:.8+.2*p,boxShadow:`9px 10px 0 ${C.ink}`}}><span style={{fontFamily:display,fontSize:70}}>{label}</span></Paper>};
const Kit=()=> <Scene><Photo src={photo.modelagem} delay={18} right/><Tag>A GENTE LEVA</Tag><div style={{height:18}}/><Tag color={C.teal} delay={11}>TUDO.</Tag><div style={{position:'relative',zIndex:2,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,marginTop:95}}>{[['VR',C.teal],['IA',C.orange],['3D',C.yellow],['BOT',C.paper]].map(([n,c],i)=><KitCard key={n} label={n} color={c} delay={23+i*7}/>)}</div></Scene>;
const Workshop=()=>{const f=useCurrentFrame(),items=[['IA','INTELIGÊNCIA\nARTIFICIAL',C.orange],['⌘','ROBÓTICA LEGO',C.yellow],['VR','REALIDADE VIRTUAL',C.teal],['↗','BRAÇO ROBÓTICO',C.orange],['3D','IMPRESSÃO 3D',C.yellow]],active=Math.min(4,Math.floor(f/96)),x=items[active],p=enter(f%96,0,14,pop);return <Scene><Photo src={photo.oculos} delay={24}/><Tag fontSize={145}>TECH.</Tag><Paper style={{position:'relative',zIndex:2,marginTop:105,height:680,display:'grid',placeItems:'center',textAlign:'center',border:`11px solid ${x[2]}`,boxShadow:`18px 19px 0 ${C.ink}`,rotate:'-2deg'}}><div style={{opacity:p,scale:.72+p*.28}}><div style={{fontFamily:display,color:x[2],fontSize:245,lineHeight:.75,textShadow:`8px 8px 0 ${C.ink}`}}>{x[0]}</div><div style={{fontFamily:display,whiteSpace:'pre-line',fontSize:63,lineHeight:.88,marginTop:55}}>{x[1]}</div></div></Paper><div style={{display:'flex',gap:11,marginTop:55}}>{items.map((a,i)=><div key={a[1]} style={{height:18,flex:1,background:i<=active?a[2]:`${C.ink}44`,boxShadow:i===active?`4px 4px 0 ${C.ink}`:undefined}}/>)}</div></Scene>};
const Steps=()=> <Scene><Tag>É SIMPLES</Tag><div style={{marginTop:95}}><Step n="01" text="Reservar um dia" delay={12}/><Step n="02" text="Organizar as autorizações" delay={25}/></div></Scene>;
const Step=({n,text,delay}:{n:string;text:string;delay:number})=>{const f=useCurrentFrame(),p=enter(f,delay,16);return <Paper style={{marginBottom:38,display:'flex',justifyContent:'center',alignItems:'center',gap:28,opacity:p,translate:`${45*(1-p)}px 0`,boxShadow:`12px 13px 0 ${C.ink}`}}><b style={{fontFamily:display,color:C.orange,fontSize:67}}>{n}</b><span style={{fontFamily:display,fontSize:48,lineHeight:.9}}>{text}</span></Paper>};
const Contact=()=> <Scene><Photo src={photo.robo} delay={8} right/><div style={{position:'relative',zIndex:2}}><Tag>SUA ESCOLA</Tag><div style={{height:22}}/><Tag color={C.teal} delay={12}>É A PRÓXIMA.</Tag><Paper style={{marginTop:85,fontFamily:display,fontSize:35,overflowWrap:'anywhere',boxShadow:`10px 11px 0 ${C.ink}`}}>leter.colatina@ifes.edu.br</Paper></div></Scene>;
const End=()=> <Scene><div style={{paddingTop:350,textAlign:'center'}}><div style={{fontFamily:display,fontSize:112,letterSpacing:9,color:C.paper,textShadow:`10px 10px 0 ${C.ink}`}}>LETER</div><div style={{fontFamily:body,fontWeight:800,fontSize:48,marginTop:50}}>Tecnologia. Aprendizado. Futuro.</div><Paper color={C.yellow} style={{display:'inline-block',marginTop:100,fontFamily:display,fontSize:39,boxShadow:`10px 11px 0 ${C.ink}`}}>SOLICITE UMA VISITA</Paper></div></Scene>;
export const LeterVideo=()=> <AbsoluteFill><Sequence durationInFrames={150}><Intro/></Sequence><Sequence from={150} durationInFrames={210}><Offer/></Sequence><Sequence from={360} durationInFrames={390}><Kit/></Sequence><Sequence from={750} durationInFrames={510}><Workshop/></Sequence><Sequence from={1260} durationInFrames={210}><Kit/></Sequence><Sequence from={1470} durationInFrames={210}><Steps/></Sequence><Sequence from={1680} durationInFrames={450}><Contact/></Sequence><Sequence from={2130} durationInFrames={120}><End/></Sequence></AbsoluteFill>;
